Fixed reference to mule.env property in global.xml
Replaced mule.envt with mule.env as defined in the properties file to fix the following exception:
ERROR 2018-12-07 14:40:23,561 [main] org.mule.module.launcher.application.DefaultMuleApplication: null
java.io.FileNotFoundException: class path resource [properties/globalweather-${mule.envt}.properties] cannot be opened because it does not exist